// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPI_GESTION_HOGAR.Datos;

#nullable disable

namespace TPI_GESTION_HOGAR.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217112441_TablasRegistros")]
    partial class TablasRegistros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Agresor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaNac")
                        .HasColumnType("date");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdRegistro")
                        .HasColumnType("int");

                    b.Property<string>("Locaclidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelEducativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RegistroId");

                    b.ToTable("Agresores");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Denuncia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdRegistro")
                        .HasColumnType("int");

                    b.Property<int?>("NroExp")
                        .HasColumnType("int");

                    b.Property<int?>("NroIPP")
                        .HasColumnType("int");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RegistroId");

                    b.ToTable("Denuncias");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Egreso", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ApellidoRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DNIRef")
                        .HasColumnType("int");

                    b.Property<string>("DomicilioRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("Idregistro")
                        .HasColumnType("int");

                    b.Property<string>("LocaclidadRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Egresos");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Habitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacidad")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("IdRegistro")
                        .HasColumnType("int");

                    b.Property<int>("NroHabitacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Hijo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaNac")
                        .HasColumnType("date");

                    b.Property<int>("IDMadre")
                        .HasColumnType("int");

                    b.Property<int>("MujerID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MujerID");

                    b.ToTable("Hijos");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Medida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DenunciaID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDenuncia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DenunciaID");

                    b.ToTable("Medidas");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Mujer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaNac")
                        .HasColumnType("date");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locaclidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelEducativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Mujeres");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Observacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdRegistro")
                        .HasColumnType("int");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.Property<string>("Suceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegistroId");

                    b.ToTable("Observaciones");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EgresoID")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaEgreso")
                        .HasColumnType("date");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("int");

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("int");

                    b.Property<int>("IdMujer")
                        .HasColumnType("int");

                    b.Property<int>("MujerID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EgresoID");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("MujerID");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Agresor", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Registro", "Registro")
                        .WithMany("Agresores")
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Denuncia", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Registro", "Registro")
                        .WithMany("Denuncias")
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Hijo", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Mujer", "Mujer")
                        .WithMany("Hijos")
                        .HasForeignKey("MujerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mujer");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Medida", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Denuncia", "Denuncia")
                        .WithMany("Medida")
                        .HasForeignKey("DenunciaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Denuncia");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Observacion", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Registro", "Registro")
                        .WithMany("Observaciones")
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Registro", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Egreso", "Egreso")
                        .WithMany()
                        .HasForeignKey("EgresoID");

                    b.HasOne("TPI_GESTION_HOGAR.Models.Habitacion", "Habitacion")
                        .WithMany("Registros")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI_GESTION_HOGAR.Models.Mujer", "Mujer")
                        .WithMany()
                        .HasForeignKey("MujerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Egreso");

                    b.Navigation("Habitacion");

                    b.Navigation("Mujer");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Denuncia", b =>
                {
                    b.Navigation("Medida");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Habitacion", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Mujer", b =>
                {
                    b.Navigation("Hijos");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Registro", b =>
                {
                    b.Navigation("Agresores");

                    b.Navigation("Denuncias");

                    b.Navigation("Observaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
