// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPI_GESTION_HOGAR.Datos;

#nullable disable

namespace TPI_GESTION_HOGAR.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322083348_crear_tabla_configuracion")]
    partial class crear_tabla_configuracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Agresor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FechaNac")
                        .HasColumnType("date");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelEducativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vinculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RegistroId");

                    b.ToTable("Agresores");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Condicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MujerId")
                        .HasColumnType("int");

                    b.Property<int>("ObservacionCondicionId")
                        .HasColumnType("int");

                    b.Property<int>("TipoCondicionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MujerId");

                    b.HasIndex("ObservacionCondicionId");

                    b.HasIndex("TipoCondicionId");

                    b.ToTable("Condiciones");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Configuracion");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Denuncia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int?>("NroExp")
                        .HasColumnType("int");

                    b.Property<int?>("NroIPP")
                        .HasColumnType("int");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RegistroId");

                    b.ToTable("Denuncias");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Egreso", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ApellidoRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DNIRef")
                        .HasColumnType("int");

                    b.Property<string>("DomicilioRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("LocalidadRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RegistroId")
                        .IsUnique();

                    b.ToTable("Egresos");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Habitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacidad")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("NroHabitacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Habitaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidad = 5,
                            Estado = true,
                            NroHabitacion = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacidad = 5,
                            Estado = true,
                            NroHabitacion = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacidad = 5,
                            Estado = true,
                            NroHabitacion = 3
                        },
                        new
                        {
                            Id = 4,
                            Capacidad = 5,
                            Estado = true,
                            NroHabitacion = 4
                        },
                        new
                        {
                            Id = 5,
                            Capacidad = 5,
                            Estado = true,
                            NroHabitacion = 5
                        },
                        new
                        {
                            Id = 6,
                            Capacidad = 5,
                            Estado = true,
                            NroHabitacion = 6
                        });
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Hijo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaNac")
                        .HasColumnType("date");

                    b.Property<int>("MujerId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MujerId");

                    b.ToTable("Hijos");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Medida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DenunciaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoMedidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DenunciaId");

                    b.HasIndex("TipoMedidaId");

                    b.ToTable("Medidas");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Mujer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("FechaNac")
                        .HasColumnType("date");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelEducativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Mujeres");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Novedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsPaseDeGuardia")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("Novedades");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Observacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.Property<string>("Suceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegistroId");

                    b.ToTable("Observaciones");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.ObservacionCondicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ObservacionCondiciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "En Tratamiento Médico"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Sin Tratamiento Actual"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Requiere Atención/Derivación"
                        });
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaNac")
                        .HasColumnType("date");

                    b.Property<int>("Legajo")
                        .HasColumnType("int");

                    b.Property<string>("Localidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("Legajo")
                        .IsUnique();

                    b.ToTable("Personal");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Recordatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Importante")
                        .HasColumnType("bit");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("int");

                    b.Property<bool>("Resuelto")
                        .HasColumnType("bit");

                    b.Property<string>("ResultadoObservacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.HasIndex("RegistroId");

                    b.ToTable("Recordatorios");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int?>("HabitacionId")
                        .HasColumnType("int");

                    b.Property<int>("MujerID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("MujerID");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Equipo Tecnico"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Operadora"
                        });
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Seguimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.HasIndex("RegistroId");

                    b.ToTable("Seguimientos");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.TipoCondicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoCondiciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Enfermedad Crónica"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Discapacidad Física"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Discapacidad Intelectual/Mental"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Adicción (Consumo Problemático)"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Otra Condición Médica"
                        });
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.TipoMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposMedidas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Prohibición de acercamiento (Perimetral)"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Exclusión del hogar del agresor"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Entrega de Botón Antipánico / Aplicación Móvil"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Cese de actos de perturbación / hostigamiento"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Restitución de efectos personales"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Ronda policial periódica en el domicilio"
                        });
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.TipoTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoTurnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Mañana (08:00 a 14:00)"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Tarde (14:00 a 20:00)"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Noche (20:00 a 08:00)"
                        });
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Turno", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonalOpcId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTurnoId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PersonalId");

                    b.HasIndex("PersonalOpcId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("Fecha", "TipoTurnoId")
                        .IsUnique();

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("PersonalId")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Agresor", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Registro", "Registro")
                        .WithMany("Agresores")
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Condicion", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Mujer", "Mujer")
                        .WithMany("Condiciones")
                        .HasForeignKey("MujerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI_GESTION_HOGAR.Models.ObservacionCondicion", "ObservacionCondicion")
                        .WithMany("Condicion")
                        .HasForeignKey("ObservacionCondicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI_GESTION_HOGAR.Models.TipoCondicion", "TipoCondicion")
                        .WithMany("Condiciones")
                        .HasForeignKey("TipoCondicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mujer");

                    b.Navigation("ObservacionCondicion");

                    b.Navigation("TipoCondicion");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Denuncia", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Registro", "Registro")
                        .WithMany("Denuncias")
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Egreso", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Registro", "Registro")
                        .WithOne("Egreso")
                        .HasForeignKey("TPI_GESTION_HOGAR.Models.Egreso", "RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Hijo", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Mujer", "Mujer")
                        .WithMany("Hijos")
                        .HasForeignKey("MujerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mujer");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Medida", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Denuncia", "Denuncia")
                        .WithMany("Medida")
                        .HasForeignKey("DenunciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI_GESTION_HOGAR.Models.TipoMedida", "TipoMedida")
                        .WithMany()
                        .HasForeignKey("TipoMedidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Denuncia");

                    b.Navigation("TipoMedida");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Novedad", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Observacion", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Registro", "Registro")
                        .WithMany("Observaciones")
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Recordatorio", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI_GESTION_HOGAR.Models.Registro", "Registro")
                        .WithMany()
                        .HasForeignKey("RegistroId");

                    b.Navigation("Personal");

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Registro", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Habitacion", "Habitacion")
                        .WithMany("Registros")
                        .HasForeignKey("HabitacionId");

                    b.HasOne("TPI_GESTION_HOGAR.Models.Mujer", "Mujer")
                        .WithMany()
                        .HasForeignKey("MujerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Mujer");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Seguimiento", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI_GESTION_HOGAR.Models.Registro", "Registro")
                        .WithMany("Seguimientos")
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Turno", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Personal", "Personal")
                        .WithMany("Turnos")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPI_GESTION_HOGAR.Models.Personal", "PersonalOpc")
                        .WithMany("TurnosOpcionales")
                        .HasForeignKey("PersonalOpcId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TPI_GESTION_HOGAR.Models.TipoTurno", "TipoTurno")
                        .WithMany("Turnos")
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");

                    b.Navigation("PersonalOpc");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Usuario", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Personal", "Personal")
                        .WithOne("Usuario")
                        .HasForeignKey("TPI_GESTION_HOGAR.Models.Usuario", "PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI_GESTION_HOGAR.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Denuncia", b =>
                {
                    b.Navigation("Medida");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Habitacion", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Mujer", b =>
                {
                    b.Navigation("Condiciones");

                    b.Navigation("Hijos");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.ObservacionCondicion", b =>
                {
                    b.Navigation("Condicion");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Personal", b =>
                {
                    b.Navigation("Turnos");

                    b.Navigation("TurnosOpcionales");

                    b.Navigation("Usuario")
                        .IsRequired();
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Registro", b =>
                {
                    b.Navigation("Agresores");

                    b.Navigation("Denuncias");

                    b.Navigation("Egreso");

                    b.Navigation("Observaciones");

                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.TipoCondicion", b =>
                {
                    b.Navigation("Condiciones");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.TipoTurno", b =>
                {
                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
