// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPI_GESTION_HOGAR.Datos;

#nullable disable

namespace TPI_GESTION_HOGAR.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218124623_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Agresor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaNac")
                        .HasColumnType("date");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locaclidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelEducativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RegistroId");

                    b.ToTable("Agresores");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Condicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MujerId")
                        .HasColumnType("int");

                    b.Property<int>("ObservacionCondicionId")
                        .HasColumnType("int");

                    b.Property<int>("TipoCondicionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MujerId");

                    b.HasIndex("ObservacionCondicionId");

                    b.HasIndex("TipoCondicionId")
                        .IsUnique();

                    b.ToTable("Condiciones");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Denuncia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int?>("NroExp")
                        .HasColumnType("int");

                    b.Property<int?>("NroIPP")
                        .HasColumnType("int");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RegistroId");

                    b.ToTable("Denuncias");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Egreso", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ApellidoRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DNIRef")
                        .HasColumnType("int");

                    b.Property<string>("DomicilioRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("LocaclidadRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RegistroId")
                        .IsUnique();

                    b.ToTable("Egresos");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Habitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacidad")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("NroHabitacion")
                        .HasColumnType("int");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Hijo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaNac")
                        .HasColumnType("date");

                    b.Property<int>("MujerId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MujerId");

                    b.ToTable("Hijos");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Medida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DenunciaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DenunciaId");

                    b.ToTable("Medidas");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Mujer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaNac")
                        .HasColumnType("date");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locaclidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelEducativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Mujeres");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Observacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.Property<string>("Suceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegistroId");

                    b.ToTable("Observaciones");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.ObservacionCondicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ObservacionCondiciones");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Personal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaNac")
                        .HasColumnType("date");

                    b.Property<int>("Legajo")
                        .HasColumnType("int");

                    b.Property<string>("Locaclidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TurnoID")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("TurnoID");

                    b.ToTable("Personal");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaEgreso")
                        .HasColumnType("date");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("int");

                    b.Property<int>("MujerID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("MujerID");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.TipoCondicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoCondiciones");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.TipoTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoTurnos");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Turno", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("Horas")
                        .HasColumnType("int");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTurnoId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TipoTurnoId")
                        .IsUnique();

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId")
                        .IsUnique();

                    b.HasIndex("RolId")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Agresor", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Registro", "Registro")
                        .WithMany("Agresores")
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Condicion", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Mujer", "Mujer")
                        .WithMany("Condiciones")
                        .HasForeignKey("MujerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI_GESTION_HOGAR.Models.ObservacionCondicion", "ObservacionCondicion")
                        .WithMany("Condicion")
                        .HasForeignKey("ObservacionCondicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI_GESTION_HOGAR.Models.TipoCondicion", "TipoCondicion")
                        .WithOne("Condicion")
                        .HasForeignKey("TPI_GESTION_HOGAR.Models.Condicion", "TipoCondicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mujer");

                    b.Navigation("ObservacionCondicion");

                    b.Navigation("TipoCondicion");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Denuncia", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Registro", "Registro")
                        .WithMany("Denuncias")
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Egreso", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Registro", "Registro")
                        .WithOne("Egreso")
                        .HasForeignKey("TPI_GESTION_HOGAR.Models.Egreso", "RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Hijo", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Mujer", "Mujer")
                        .WithMany("Hijos")
                        .HasForeignKey("MujerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mujer");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Medida", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Denuncia", "Denuncia")
                        .WithMany("Medida")
                        .HasForeignKey("DenunciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Denuncia");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Observacion", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Registro", "Registro")
                        .WithMany("Observaciones")
                        .HasForeignKey("RegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Personal", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Turno", "Turno")
                        .WithMany("Personal")
                        .HasForeignKey("TurnoID");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Registro", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Habitacion", "Habitacion")
                        .WithMany("Registros")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI_GESTION_HOGAR.Models.Mujer", "Mujer")
                        .WithMany()
                        .HasForeignKey("MujerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Mujer");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Turno", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.TipoTurno", "TipoTurno")
                        .WithOne("Turno")
                        .HasForeignKey("TPI_GESTION_HOGAR.Models.Turno", "TipoTurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Usuario", b =>
                {
                    b.HasOne("TPI_GESTION_HOGAR.Models.Personal", "Personal")
                        .WithOne("Usuario")
                        .HasForeignKey("TPI_GESTION_HOGAR.Models.Usuario", "PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TPI_GESTION_HOGAR.Models.Rol", "Rol")
                        .WithOne("Usuario")
                        .HasForeignKey("TPI_GESTION_HOGAR.Models.Usuario", "RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Denuncia", b =>
                {
                    b.Navigation("Medida");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Habitacion", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Mujer", b =>
                {
                    b.Navigation("Condiciones");

                    b.Navigation("Hijos");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.ObservacionCondicion", b =>
                {
                    b.Navigation("Condicion");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Personal", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Registro", b =>
                {
                    b.Navigation("Agresores");

                    b.Navigation("Denuncias");

                    b.Navigation("Egreso");

                    b.Navigation("Observaciones");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Rol", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.TipoCondicion", b =>
                {
                    b.Navigation("Condicion");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.TipoTurno", b =>
                {
                    b.Navigation("Turno");
                });

            modelBuilder.Entity("TPI_GESTION_HOGAR.Models.Turno", b =>
                {
                    b.Navigation("Personal");
                });
#pragma warning restore 612, 618
        }
    }
}
